[project]
name = "majong"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "shapely>=2.1.2",
    "streamlit>=1.52.2",
    "ultralytics>=8.3.241",
]
